### ISSUE TITLE
prepare_deployments

### ISSUE THREAD

**Issue by felixSchl** [pixelcog/opsworks-vm#10]
It might be a lack of understanding on my behalf (probably), but it seems odd that [`prepare_deployment`](https://github.com/pixelcog/opsworks-vm/blob/049d0bccb23897f5f5000412038aebae560480c9/opsworks/opsworks.rb#L283) does not resolve the full path `"/vagrant/#{path}"`. Mysteriously, the shipped example worked for me, but my own stuff doesn't. I have renamed my apps and so on, but it all looks consistent with what you have, apart from leaving out php-related recipes and so on. Once I resolve to the full path `"/vagrant/#{path}"` it all works.

**Comment by mikegreiling** [comment]
What value were you using for `deploy.{app-name}.scm.repository` within your chef json?  Are you saying that you tried a relative path and it didn't work until you specified an absolute path?

**Comment by mikegreiling** [comment]
Any relative path should be interpreted within the context of `/vagrant` as the current working directory, so in the case of the example php app, `dev/simple-php` should resolve to `/vagrant/dev/simple-php`.
