### ISSUE TITLE
my.cnf template issue

### ISSUE THREAD

**Issue by threesquared** [pixelcog/opsworks-vm#12]
Whenever I try to provision a database instance with `db-master.json` I get the error `(undefined method `name' for nil:NilClass) on line #1:` it seems that chef is using the chef mysql cookbook [template file](https://github.com/chef-cookbooks/mysql/blob/master/templates/default/my.cnf.erb) which depends on the a config array with the name attr instead of the one provided [with opsworks](https://github.com/aws/opsworks-cookbooks/blob/release-chef-11.10/mysql/templates/default/my.cnf.erb)? I don't have the mysql cookbook specified in my Berksfile so why would it be using that erb file?

**Comment by threesquared** [comment]
For some reason this was caused by adding the composer cookbook to the Berksfile in my custom cookbooks. Removing the line `cookbook 'composer', '~> 2.2.1'` fixed this issue.

**Comment by mikegreiling** [comment]
glad you were able to figure out the issue
