### ISSUE TITLE
File mount is failing

### ISSUE THREAD

**Issue by kurtisnelson** [pixelcog/opsworks-vm#2]
Vagrant up is failing.

```
==> app: Mounting shared folders...
    app: /vagrant => /Users/kurt/workspace/monsieur/bouncer
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` vagrant /vagrant
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` vagrant /vagrant

The error output from the last command was:

/sbin/mount.vboxsf: mounting failed with the error: No such device
```

[Vagrant File](https://github.com/MonsieurCode/bouncer/blob/master/Vagrantfile)

**Comment by mikegreiling** [comment]
what version of VirtualBox are you running?  and which rake task did you run to build your image?

as the error indicates, it is attempting and failing to mount your current directory to /vagrant within the guest vm.

**Comment by mikegreiling** [comment]
I just cloned and tested the build process and example project within this repo with VirtualBox 4.3.22 and did not encounter the issue.  I'll try again after updating to VB 4.3.26 and see if that causes the issue.

**Comment by kurtisnelson** [comment]
`rake virtualbox:build`
`rake virtualbox:install`
`vagrant up`

I updated to 4.3.26 and rebuilt, same problem. I'm wondering if setting my scm path to '.' in the JSON is messing with it?

**Comment by mikegreiling** [comment]
I don't think so, it appears to be running into problems before the provisioner even runs.

Try running `vagrant up` in the example project directory of this repository and verify that it works.  If not, run `vagrant ssh` to log into your guest vm and let me know the output of `lsmod`

**Comment by kurtisnelson** [comment]
Totally different error in the example:

```
==> app: Compiled Resource:
==> app: ------------------
==> app: # Declared in /var/lib/aws/opsworks/cache.stage1/cookbooks/opsworks_custom_cookbooks/recipes/checkout.rb:29:in `from_file'
==> app:
==> app: git("Download Custom Cookbooks") do
==> app:   provider Chef::Provider::Git
==> app:   action [:checkout]
==> app:   retries 0
==> app:   retry_delay 2
==> app:   destination "/opt/aws/opsworks/current/site-cookbooks"
==> app:   enable_submodules true
==> app:   enable_checkout true
==> app:   revision "HEAD"
==> app:   remote "origin"
==> app:   checkout_branch "deploy"
==> app:   cookbook_name "opsworks_custom_cookbooks"
==> app:   recipe_name "checkout"
==> app:   user "root"
==> app:   group "root"
==> app:   repository "/tmp/vagrant-opsworks20150330-1375-ioh2gt"
==> app:   not_if { #code block }
==> app: end
==> app:
==> app:
==> app:
==> app: [2015-03-30T21:40:00+00:00] INFO: Running queued delayed notifications before re-raising exception
==> app: [2015-03-30T21:40:00+00:00] ERROR: Running exception handlers
==> app: [2015-03-30T21:40:00+00:00] ERROR: Exception handlers complete
==> app: [2015-03-30T21:40:00+00:00] FATAL: Stacktrace dumped to /var/lib/aws/opsworks/cache.stage1/chef-stacktrace.out
==> app: [2015-03-30T21:40:00+00:00] ERROR: git[Download Custom Cookbooks] (opsworks_custom_cookbooks::checkout line 29) had an error: Chef::Exceptions::UnresolvableGitReference: Unable to parse SHA reference for 'HEAD' in repository '/tmp/vagrant-opsworks20150330-1375-ioh2gt'. Verify your (case-sensitive) repository URL and revision.
==> app: `git ls-remote` output:
==> app: [2015-03-30T21:40:00+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
==> app: Waiting for process 1395
==> app: pid 1395 exited with status 256, exit code: 1 (time=11 sec)
==> app: [2015-03-30 21:40:00] ERROR [opsworks-agent(1388)]: Chef run failed with exitcode 1
==> app: error: Chef run failed with exitcode 1
```

**Comment by mikegreiling** [comment]
ah, whoops.  that means you never initialized the submodules in this repo.

run `git submodule init && git submodule update` then try again

**Comment by mikegreiling** [comment]
may want to `vagrant destroy` as well to start fresh

**Comment by kurtisnelson** [comment]
That is working now. So it's something with my config somehow.

**Comment by mikegreiling** [comment]
try getting the result of `lsmod` from your guest vm and printing it here... it should contain vboxguest.

**Comment by kurtisnelson** [comment]
It's there.

```
vagrant@opsworks-vagrant:~$ lsmod
Module                  Size  Used by
ppdev                  17671  0
nfsd                  279845  2
auth_rpcgss            59337  1 nfsd
serio_raw              13483  0
nfs_acl                12837  1 nfsd
nfs                   237583  0
lockd                  93977  2 nfs,nfsd
sunrpc                294716  6 nfs,nfsd,auth_rpcgss,lockd,nfs_acl
fscache                63988  1 nfs
i2c_piix4              22166  0
vboxguest             248459  1
parport_pc             32741  0
video                  20128  0
lp                     17759  0
parport                42348  3 lp,ppdev,parport_pc
mac_hid                13227  0
psmouse               106561  0
ahci                   34062  2
libahci                32424  1 ahci
e1000                 133256  0
pata_acpi              13053  0
```

**Comment by mikegreiling** [comment]
did you run `vagrant destroy -f` after you rebuilt the image earlier?  I'm still confused as to how it works in the example, but not in your project.

**Comment by mikegreiling** [comment]
could it be a permissions issue in the root directory of your repo?

**Comment by shanbady** [comment]
ive seen this before. in my case i was because i had ebs settings in my json config. removing this fixed it for me. do yu have ebs settings specified in your local json?

**Comment by kurtisnelson** [comment]
Here's my permissions, doesn't seem like it should be a problem

```
drwxr-xr-x  31 kurt  staff   1.0K Mar 30 18:01 bouncer
```

And [here](https://github.com/MonsieurCode/bouncer/blob/master/ops/stack.json) is my JSON. The whole project is open source if you want to take a look.

**Comment by shanbady** [comment]
It does look like you have specified the ebs recipe to run in: ops/dna/php-app.json

**Comment by kurtisnelson** [comment]
You mean [this line](https://github.com/MonsieurCode/bouncer/blob/master/ops/rails-app.json#L9)?

**Comment by shanbady** [comment]
yes

**Comment by kurtisnelson** [comment]
That fixed it, now I just have to get the rails specific stuff working right.

**Comment by mikegreiling** [comment]
Glad to see you've got it working.

Thanks @shanbady for stepping in to help resolve this.  I have not encountered the ebs issue before.
