### ISSUE TITLE
Waiting for SSH to become available

### ISSUE THREAD

**Issue by felixSchl** [pixelcog/opsworks-vm#7]
Hi, first of all a huge thank you!!!

With that out of the way, when I clone the repo and run `rake build` it downloads the image, creates the virtual machine, hard drive, port forward mappings and finally starts the machine. However, it then gets stuck on "Waiting for SSH to become available" until it finally times out. I have seen this behaviour on the 2 out 2 OSX machines that I have tried this on. Any idea?

**Comment by felixSchl** [comment]
I am taking [advice from stackoverflow](http://stackoverflow.com/a/31336953/2954634) now. I can see how it potentially timed out. I just artifically set the timeout to an hour and watch the progress with headless off. I will report back if that fixes it.

**Comment by felixSchl** [comment]
Alright, it took around half an hour or so but it worked and your example ran as well. Impressive stuff.

**Comment by mikegreiling** [comment]
Hey, sorry I missed this issue back when you posted it, someone on my [blog comments](http://pixelcog.com/blog/2015/simplify-opsworks-dev-with-packer/#comment-2088755811) reported a similar issue. Glad you were able to solve the issue on your own.
